name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # Use a stable version of Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install required dependencies
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl git
      
      # Install Docker Compose manually (since it's no longer pre-installed)
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github


      # Verify installation of Docker & Docker Compose
      - name: Verify Docker and Docker Compose Installation
        run: |
          docker --version
          docker compose version  # Uses the new syntax (without a hyphen)

      # Install MongoDB 6.0
      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg curl lsb-release
          sudo rm -f /usr/share/keyrings/mongodb-server-keyring.gpg

          # Import MongoDB public key
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-keyring.gpg

          # Use Ubuntu 22.04 repository instead of 24.04
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-keyring.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

          sudo apt-get update
          sudo apt-get install -y mongodb-org

          # Start and enable MongoDB service (correct service name: mongod)
          sudo systemctl start mongod
          sudo systemctl enable mongod

      # Build and start Docker containers
      - name: Build and Run Containers
        run: docker compose up --build -d

      # Run backend tests inside the container
      - name: Run Backend Tests
        run: docker compose exec backend npm test

      # Shut down containers after tests
      - name: Shut Down Containers
        run: docker compose down
